# -*- coding: utf-8 -*-
"""ReconecimentoDeFaces.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0cG7aPLt1Qov-iO0z3YqAodlRGMxDTa

# Aula 1 - Visão Computacional
"""

import cv2

from google.colab import drive
drive.mount('/content/drive')

imagem = cv2.imread("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Images/people1.jpg")

imagem.shape

from google.colab.patches import cv2_imshow
cv2_imshow(imagem)

imagem = cv2.resize(imagem, (800, 600))
imagem.shape

cv2_imshow(imagem)

img_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

img_cinza.shape

cv2_imshow(img_cinza)

dt_facial = cv2.CascadeClassifier("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Cascades/haarcascade_frontalface_default.xml")

dt = dt_facial.detectMultiScale(img_cinza, scaleFactor = 1.3)

for (x, y, w, h) in dt:
  cv2.rectangle(imagem, (x, y), (x + w, y + h), (0, 255,0), 5)
cv2_imshow(imagem)

cv2.imread("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Images/people2.jpg")

img2 = cv2.imread("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Images/people2.jpg")
img2_cinza = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
dt_facial = cv2.CascadeClassifier("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Cascades/haarcascade_frontalface_default.xml")
dt2 = dt_facial.detectMultiScale(img2_cinza, scaleFactor= 1.2, minNeighbors=4, minSize=(32, 32))
for (x, y, w, h) in dt2:
  cv2.rectangle(img2, (x, y), (x + w, y + h), (0, 255,0), 5)
cv2_imshow(img2)

img3 = cv2.imread("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Images/people1.jpg")
img3_cinza = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
dt_facial = cv2.CascadeClassifier("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Cascades/haarcascade_frontalface_default.xml")
dt3 = dt_facial.detectMultiScale(img3_cinza, scaleFactor= 1.3, minNeighbors=4, minSize=(32, 32))
for (x, y, w, h) in dt3:
  cv2.rectangle(img3, (x, y), (x + w, y + h), (0, 255,0), 5)

dt_eyes = cv2.CascadeClassifier("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Cascades/haarcascade_eye.xml")
dt4 = dt_eyes.detectMultiScale(img3_cinza, scaleFactor= 1.2, maxSize=(66, 66))
for (x, y, w, h) in dt4:
  cv2.rectangle(img3, (x, y), (x + w, y + h), (255, 0,0), 5)
  print(w,h)

cv2_imshow(img3)

img4 = cv2.imread("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Images/car.jpg")
img4_cinza = cv2.cvtColor(img4, cv2.COLOR_BGR2GRAY)
dt_cars = cv2.CascadeClassifier("/content/drive/MyDrive/Colab Notebooks/Computação Gráfica/Cascades/cars.xml")

# Ajuste os parâmetros do detectMultiScale
dt5 = dt_cars.detectMultiScale(img4_cinza, scaleFactor=1.008, minNeighbors=3, maxSize=(40, 40), minSize=(27, 27))

for (x, y, w, h) in dt5:
  cv2.rectangle(img4, (x, y), (x + w, y + h), (0, 255,0),2)
  print(w,h)

cv2_imshow(img4)